### ISSUE TITLE
1. Select available sources to use. (user story: annotated with information)

### ISSUE THREAD

**Issue by Vennik** [ProgrammingLife2015/geex#120]

**Comment by jnieuwdorp** [comment]
Right now we'll probably only use: 
- USCS Tabel Browser, which gives annotations on coding/non-coding and Sense/anti-sense. If my assumptions are correct (I've send an email about this) I can start translating the coordinates. 
- Meta-data on Resistance causing mutations.

**Comment by jnieuwdorp** [comment]
Branch used is features/annotations. 

To Do: create seperate controller for annotations & add tests.

**Comment by jnieuwdorp** [comment]
Done
