### ISSUE TITLE
Create a runnable jar

### ISSUE THREAD

**Issue by qurben** [ProgrammingLife2015/geex#147]
Use maven to create a runnable jar.

Need to add the libnewicktree jar to the final jar.

Also fix other maven issues

**Comment by jnieuwdorp** [comment]
We get the maven warning: `[WARNING] Unable to locate Source XRef to link to - DISABLED`

Fix here: 
http://stackoverflow.com/questions/12038238/unable-to-locate-source-xref-to-link-to

**Comment by qurben** [comment]
Fixed in #149
