### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by jjpe** [ProgrammingLife2015/geex#178]
Hi team 2,

I have feedback ready for you. What email address(es) should I send it to?

Cheers,
Joey

**Comment by qurben** [comment]
All of them

**Comment by Vennik** [comment]
Maven site teampage.

**Comment by jjpe** [comment]
That is not a helpful answer since I don't have your email addresses.

**Comment by Vennik** [comment]
renevennik@gmail.com

**Comment by jjpe** [comment]
You should have access to the feedback now.
