### ISSUE TITLE
Change SA meeting time

### ISSUE THREAD

**Issue by Vennik** [ProgrammingLife2015/geex#29]
Try to change SA meeting time.

**Comment by jnieuwdorp** [comment]
Mailed all applicable TAs

**Comment by jnieuwdorp** [comment]
Sjoerd told us to contact the team we want to switch timeslot with ourselves. Doing that now

**Comment by jnieuwdorp** [comment]
Found somebody in group 5, asked him to discuss it with his team. Should hear back from him shortly

**Comment by jnieuwdorp** [comment]
Group 5 doesn't want to change.  Will email TAs again to ask the to reconsider 12.00-12.30

**Comment by jnieuwdorp** [comment]
email sent.

**Comment by jnieuwdorp** [comment]
TAs can't change the meeting time. Meeting stands. They did offer us the option to ask questions starting at 12.00
